inpage/.eslintrc.cjs
inpage/demo/App.tsx
inpage/package.json
inpage/src/Button.tsx
inpage/src/EthereumApi.ts
inpage/src/JsonRpcError.ts
inpage/src/PermissionPopup.tsx
inpage/src/WaxInPage.tsx
inpage/src/WaxStorage.ts
inpage/yarn.lock

Resolves #17.
- Make `eth_requestAccounts` return an array instead of a single address (see `eth_requestAccounts` in [EIP-1102](https://eips.ethereum.org/EIPS/eip-1102))
- Implement `eth_accounts`
- Returns array of already-connected accounts (doesn't need the user's permission)
- Enables ethers' `getSigner` method
- Use localstorage so you don't need to reconnect your address when you return/refresh
- Use the `eth_accounts` API in the demo to avoid needing to re-request accounts
- Add `disabled` state for `<Button/>` and apply it when an async callback is in progress

Updates to inpage #1

---

inpage/.eslintrc.cjs
inpage/.gitignore
inpage/README.md
inpage/demo/ConfigType.ts
inpage/demo/LinksPage.tsx
inpage/demo/config.template.ts
inpage/demo/main.tsx
inpage/package.json
inpage/scripts/dev.ts
inpage/scripts/helpers/fileExists.ts
inpage/scripts/helpers/projectPath.ts
inpage/scripts/helpers/shell.ts
inpage/scripts/setup.ts
inpage/src/EthereumApi.tsx
inpage/src/EthereumRpc.ts
inpage/src/WaxInPage.tsx
inpage/src/global.ts
inpage/tsconfig.json
inpage/yarn.lock

inpage now works with external networks!
It's as simple as configuring `rpcUrl` in `demo/config.ts`. `yarn dev` will skip running a node when you set it to something other than `http://127.0.0.1:8545`.
The contracts have these deterministic addresses:
```ts
{
entryPoint: '0x41d406bdbDD04f273353B4CB2f64d23b2ef9F2B0',
simpleAccountFactory: '0xAc1A4e82A50bc64096D43d947eDb4AE7ad3C1b5D',
greeter: '0x9631Ccf03161e6b18B179Be829E601BB6bb645c5',
}
```
You can see them at those addresses on:
- Optimism Goerli: [entryPoint](https://goerli-optimism.etherscan.io/address/0x41d406bdbDD04f273353B4CB2f64d23b2ef9F2B0), [simpleAccountFactory](https://goerli-optimism.etherscan.io/address/0xAc1A4e82A50bc64096D43d947eDb4AE7ad3C1b5D), [greeter](https://goerli-optimism.etherscan.io/address/0x9631Ccf03161e6b18B179 …

Inpage: Enable external networks

---

account-integrations/safe/package.json
account-integrations/safe/src/SafeBlsPlugin.sol
account-integrations/safe/src/utils/SafeTypechainTypesHelper.sol
account-integrations/safe/test/hardhat/SafeBlsPlugin.test.ts
account-integrations/safe/test/integration/SafeBlsPlugin.test.ts
account-integrations/safe/yarn.lock

Blocked by: https://github.com/getwax/wax/pull/52
Adding a Safe module that uses BLS sigs to verify a transaction. I added a hardhat test that submits a userOp to the entrypoint directly.  This way we don't need to run a bundler or start a node to test a module.
I'm wondering if we should reorganize our test directory.  Right now we have three forms of tests.
- **hardhat test** - all you need is `yarn hardhat test` and the tests should work. Hardhat tests are useful for verification types that are hard/not possible in solidity.
- **Integration test** - Need to run a bundler and a node separately for the tests to pass.
- **Forge tests** - just need `forge test`, and tests are written in solidity.
Should rename/organise these differently?  For example, the two ideas I have are:
- …

Safe BLS module

---

account-integrations/safe/src/SafeWebAuthnPlugin.sol
account-integrations/safe/src/lib/FCL_Webauthn.sol
account-integrations/safe/test/forge/utils/TestHelper.sol
account-integrations/safe/test/hardhat/integration/SafeWebAuthnPlugin.test.ts

Slicing calldata for a webauthn library call whilst keeping below the maximum stack depth. Closes #68

Use original library function (calldata params)

---

account-integrations/safe/package.json
account-integrations/safe/test/hardhat/integration/SafeECDSAPlugin.test.ts
account-integrations/safe/test/hardhat/integration/SafeWebAuthnPlugin.test.ts
account-integrations/safe/test/hardhat/utils/receiptOf.ts
account-integrations/safe/test/hardhat/utils/sendUserOpAndWait.ts
account-integrations/safe/yarn.lock

This PR depends on #86. Please merge that PR first.
- Remove ethers-v5 (consolidate on v6 only)
- Improve syncing with bundler using APIs instead of waiting 5 seconds
- `sendUserOpAndWait` sends a user operation and polls for the receipt
- `receiptOf` avoids double await pattern, alleviating the temptation to not wait for the receipt
`yarn hardhat test` is now much faster (not foundry fast, but still).

More cleanup for account-integrations/safe

---

account-integrations/safe/script/deploy_all.ts
account-integrations/safe/script/start.sh
account-integrations/safe/test/hardhat/integration/SafeECDSAPlugin.test.ts
account-integrations/safe/test/hardhat/integration/SafeWebAuthnPlugin.test.ts
account-integrations/safe/test/hardhat/utils/makeDevFaster.ts

- Set `pollingInterval` to 100ms if chain id is 1337 or 31337 (default = 4000ms)
- Use `dev.period=0` for instant sealing and don't enable mining
This makes `./scripts/start.sh` and `yarn hardhat test` much faster.
Before:
After:

Make dev faster

---

account-integrations/safe/src/SafeECDSAFactory.sol
account-integrations/safe/src/SafeECDSAPlugin.sol
account-integrations/safe/src/SafeECDSARecoveryPlugin.sol
account-integrations/safe/test/forge/SafeECDSAPlugin.t.sol
account-integrations/safe/test/forge/utils/SafeECDSAPluginHarness.sol
account-integrations/safe/test/hardhat/setupTests.ts

Changing the address storage on the SafeECDSAPlugin to be a mapping.  This fixes all of our current tests.  I need to do further testing but I think this should make a single SafeECDSAPlugin compatible with multiple safes.
https://github.com/getwax/wax/issues/104

Fix signature issue for ecdsa plugin

---

account-integrations/safe/src/SafeWebAuthnPlugin.sol

Clarify webauthn decoding from pr comments

---

demos/inpage/.eslintignore
demos/inpage/hardhat/test/Greeter.ts
demos/inpage/src/SafeSingletonFactory.ts
demos/inpage/src/WaxInPage.tsx
demos/inpage/src/WaxStorage.ts
demos/inpage/src/compatibility.ts
demos/inpage/src/helpers/assert.ts

- Symlink in hardhat/lib causes conflicts and doesn't make sense to lint in this context
- Remove unnecessary disables which surface when using `yarn lint`
- Disable `no-debugger` for debugger statement in `assert`

Fix linting

---

account-integrations/safe/script/start-hardhat.sh

Just a variation of `./script/start.sh` which uses hardhat instead of geth.
This requires using the bundler in unsafe mode.
Using hardhat can be advantageous for the different diagnostics it provides, especially integration with `console.log`.

Add script for starting with hardhat

---

account-integrations/safe/src/SafeBlsPlugin.sol
account-integrations/safe/src/SafeECDSAPlugin.sol
account-integrations/safe/src/SafeWebAuthnPlugin.sol
account-integrations/safe/test/hardhat/integration/SafeECDSAPlugin.test.ts

Resolves #89 by using `HandlerContext` to access `_msgSender()` and check that it's `this` or the entry point.

Fix unauthorized access

---

account-integrations/safe/src/SafeCompressionFactory.sol
account-integrations/safe/src/SafeCompressionPlugin.sol
account-integrations/safe/src/compression
account-integrations/safe/test/hardhat/integration/SafeCompressionPlugin.test.ts
account-integrations/safe/test/hardhat/utils/receiptOf.ts

Resolves #113.
(#113 would originally have included applying this in the in-page wallet as well, but I made that a separate issue that can build on top of this work: #119).

Add compression plugin

---

demos/inpage/.gitignore
demos/inpage/demo/DemoContext.ts
demos/inpage/demo/config/ConfigType.ts
demos/inpage/demo/config/config.template.ts
demos/inpage/demo/config/config.testnet.ts
demos/inpage/src/AdminPopup.tsx
demos/inpage/src/WaxInPage.tsx

Right now when loading [the deployed demo](https://main.d2q4o4f8gnoq5j.amplifyapp.com/) the user needs to put in a funded wallet so the contracts can be deployed.  This change allows us to see a default deployer wallet that we can fund.  This will make the UX a little more streamlined for dev connect.  I also use an ENV variable so we don't have to commit the seed phrase.
For more context see this convo: https://github.com/getwax/wax/pull/114#issuecomment-1759471539

Allow passing a default deployer seed phrase

---

demos/inpage/.eslintrc.cjs
demos/inpage/demo/ConfigType.ts
demos/inpage/demo/LinksPage.tsx
demos/inpage/demo/PageRouter.tsx
demos/inpage/demo/SendEthPage.css
demos/inpage/demo/SendEthPage.tsx
demos/inpage/demo/config.template.ts
demos/inpage/demo/main.tsx
demos/inpage/hardhat/contracts/imports.sol
demos/inpage/src/EthereumApi.tsx
demos/inpage/src/EthereumRpc.ts
demos/inpage/src/WaxInPage.tsx
demos/inpage/src/accounts/AccountData.ts
demos/inpage/src/accounts/SafeCompressionAccountWrapper.ts
demos/inpage/src/bundlers/SimulatedBundler.ts
demos/inpage/src/ethereumRequest.ts
demos/inpage/src/helpers/encodeUtils.ts

This PR depends on #120, please merge that PR first.
Resolves #119.
Adds `SafeCompressionAccount` to in-page wallet:
Adds dApp for sending eth:
New logs with prefix `logBytes` for logging about how many bytes are involved in different things:
Here we can see that 25 bytes are needed by `decompressAndPerform` to tell it to send 0.1 ETH to the specified address (in future reducible to 8 bytes if the recipient is the in the address registry). Note that this doesn't include specifying the gas limit and other fields of the `userOp`, those are not part of account-level compression and will instead be included in top-level compression (#112).
This still requires 100 bytes of calldata into the account to encode the `decompressAndPerform` call as a whole (4 bytes to specify method, 32 bytes to say …

Use account-level compression in in-page demo

---

account-integrations/safe/src/SafeBlsPlugin.sol
account-integrations/safe/src/SafeCompressionPlugin.sol
account-integrations/safe/src/SafeECDSAPlugin.sol
account-integrations/safe/src/SafeWebAuthnPlugin.sol
account-integrations/safe/src/utils/Safe4337Base.sol
account-integrations/safe/test/forge/SafeBlsPlugin.t.sol
account-integrations/safe/test/forge/SafeECDSAPlugin.t.sol
account-integrations/safe/test/forge/SafeWebAuthnPlugin.t.sol

This PR depends on #120, please merge that PR first.
Followup for #118.
Changes:
- Override `_requireFromEntryPoint()` to use `_msgSender()` (comment)
- Allows removal of `validateUserOp` overrides because the `BaseAccount` version now does the correct thing
- Prefer only allowing calls from entry point (comment)
- Implements the above as a common base class `Safe4337Base` which also allows deduplicating:
- `_payPrefund()`
- `_validateNonce()`
- `Safe4337Base` also implements `_currentSafe()` which helps clear up confusion for referring to the safe

Fix auth followup / Safe4337Base

---

demos/inpage/demo/DemoContext.ts
demos/inpage/demo/LinksPage.tsx
demos/inpage/demo/PageRouter.tsx
demos/inpage/demo/Recovery.css
demos/inpage/demo/Recovery.tsx
demos/inpage/hardhat/contracts/imports.sol
demos/inpage/src/accounts/SafeECDSAAccountWrapper.ts
demos/inpage/src/accounts/execution.ts

This PR adds a basic recovery flow to the inpage. This includes setting up the recovery module and also recovering the account via the module.
There are a few improvements to be made to this flow, notably:
- Remove use of two seed phrases for recovery - not an ideal flow but was a quick way to get the demo working in it's current form
- Send txs via bundler (as opposed to calling contracts the non-4337 way)
- Deploy recovery plugin on initial contracts deploy (can't do this yet as tightly coupled to a single account rather than being a singleton that any account can use)
- The pattern so far has been a ts wrapper class per module. The recovery module is a little different as it is currently not a standalone module that executes txs. So we should explore how we want to manage this as a …

75 demonstrate recovery module in in page wallet

---

account-integrations/safe/foundry.toml
account-integrations/safe/src/SafeECDSAPlugin.sol
account-integrations/safe/src/SafeECDSARecoveryPlugin.sol
account-integrations/safe/test/forge/SafeECDSARecoveryPlugin.t.sol
account-integrations/safe/test/forge/utils/TestHelper.sol
account-integrations/safe/test/hardhat/SafeECDSARecoveryPlugin.test.ts
demos/inpage/demo/Recovery.tsx
demos/inpage/hardhat/hardhat.config.ts
demos/inpage/src/WaxInPage.tsx
demos/inpage/src/accounts/SafeECDSAAccountWrapper.ts

This PR:
1. Updates `SafeECDSARecoveryPlugin` so that it can be used by multiple accounts and is not tightly coupled to a single `SafeECDSAPlugin`.
2. Updates inpage demo to use updated contracts
3. Updates inpage demo to take private keys instead of seed phrases. Private keys are easier to source when running the demo (when using funded hardhat accounts), compared to seed phrases where you have the extra step of funding them first. This change is just to make running through the demo easier as we can use the logged hardhat accounts. The idea is to remove the need to pass private keys or seed phrases in at all, so this is a temporary solution anyway
4. Adds a hardhat task for funding accounts
5. Adds forge tests for new contract changes

Update recovery plugin to be singleton

---

account-integrations/safe/src/SafeECDSARecoveryPlugin.sol
account-integrations/safe/test/forge/SafeECDSARecoveryPlugin.t.sol
account-integrations/safe/test/forge/utils/TestHelper.sol
account-integrations/safe/test/hardhat/SafeECDSARecoveryPlugin.test.ts

This PR:
- Improves guardian privacy by storing a hash instead of a guardian address
- Creates a `RECOVERY_HASH_DOMAIN` to improve recovery security
- Stores recovery hashes by safe address instead of owner address. This is because it is possible that a single owner can manage more than one safe. So there would be a collision when that owner enabled a guardian with their second safe.
- Passes a signature signed by the new owner to `resetEcdsaAddress` to prove recovery is accepted by the new owner
- Adds a check to ensure the module is enabled before it can be used

131 recover account via signature

---

account-integrations/compression/README.md
account-integrations/compression/src/HandleAggregatedOpsCaller.sol
account-integrations/compression/src/HandleOpsCaller.sol
account-integrations/compression/src/I4337.sol
account-integrations/compression/test/HandleAggregatedOpsCaller.t.sol
account-integrations/compression/test/HandleOpsCaller.t.sol
account-integrations/compression/test/helpers/MockEntryPoint.sol
demos/inpage/hardhat/contracts/imports.sol
demos/inpage/src/WaxInPage.tsx
demos/inpage/src/bundlers/SimulatedBundler.ts
demos/inpage/src/helpers/encodeUtils.ts

Adds top-level compression to the inpage demo. This means the internal bundler calls `HandleOpsCaller` instead of the `EntryPoint`, so that the top-level calldata can be compressed off-chain, and `HandleOpsCaller` decompresses it before passing it on to `EntryPoint`.
Send a transaction using the inpage demo. In the console you should see a log like `logBytes: EntryPoint tx is 319 bytes: ...`.
Top-level compression can be turned off using `waxInPage.setConfig({ useTopLevelCompression: false })` (in the console).
If you send another transaction, you should see a log like `logBytes: EntryPoint tx is 951 bytes: ...`.
Depending on the account type used and the type of transactions, the numbers will be different, but it should be dramatically fewer bytes when compression is enabled.
Resolves …

Use top-level compression

---

demos/inpage/src/EthereumApi.tsx
demos/inpage/src/bundlers/SimulatedBundler.ts
demos/inpage/src/helpers/encodeUtils.ts

Rounds gas-related fields up to 3 significant figures so they can be encoded in 2 bytes by pseudofloat. This results in about a 1% error in the worst case (eg 100,001 -> 101,000).
```solidity
struct UserOperation {
address sender;
uint256 nonce;
bytes initCode;
bytes callData;
uint256 callGasLimit;         // <-------------
uint256 verificationGasLimit; // <-------------
uint256 preVerificationGas;   // <------------- These fields
uint256 maxFeePerGas;         // <-------------
uint256 maxPriorityFeePerGas; // <-------------
bytes paymasterAndData;
bytes signature;
}
```
The size of `EntryPoint tx` and `EntryPoint calldata` is about 4 bytes smaller after this change. (Search `logBytes` in the dev console.)
Resolves #159.
- The `resolve …

Round up to 3 significant figures to make pseudofloats smaller

---

account-integrations/compression/src/HandleAggregatedOpsCaller.sol
account-integrations/compression/src/HandleOpsCaller.sol
account-integrations/compression/test/HandleAggregatedOpsCaller.t.sol
account-integrations/compression/test/HandleOpsCaller.t.sol
demos/inpage/src/bundlers/SimulatedBundler.ts

This PR builds on https://github.com/getwax/wax/pull/163, please merge that PR first.
When calling a compression-enabled wallet, you use `decompressAndPerform(bytes)`. This causes a lot of overhead in the solidity abi as documented in the code:
```solidity
// wax/account-integrations/compression/test/HandleOpsCaller.t.sol:132:
callData: (
// Method signature of decompressAndPerform(bytes)
hex"2d1634c5"
// Location of bytes argument
hex"0000000000000000000000000000000000000000000000000000000000000020"
// Length of bytes argument
hex"000000000000000000000000000000000000000000000000000000000000000b"
// Actual data to be decompressed inside account
hex"000102030405060708090a"
// Padding
hex"000000000000000000000000000000000000000000"
),
```
This PR introduces a new bit flag to indicate …

Compression: Fix ABI overhead for decompressAndPerform in top-level compression

---

demos/inpage/demo/LinksPage.tsx
demos/inpage/demo/PageRouter.tsx
demos/inpage/demo/RegisterAddressPage.scss
demos/inpage/demo/RegisterAddressPage.tsx
demos/inpage/package.json
demos/inpage/src/accounts/SafeCompressionAccountWrapper.ts
demos/inpage/src/bundlers/SimulatedBundler.ts
demos/inpage/src/helpers/encodeUtils.ts
demos/inpage/yarn.lock

This PR depends on https://github.com/getwax/wax/pull/165. Please merge that PR first.
- Makes use of the AddressRegistry in the inpage demo
- Makes `Add Funds` primary when the account has no funds
- Fixed bug in `encodeRegIndex`
Demo:
[![Demo video](https://img.youtube.com/vi/En-i1brvXss/0.jpg)](https://www.youtube.com/watch?v=En-i1brvXss)
Btw I forgot to mention that in a real product/deployment you'd probably proactively register the user's address without them doing it explicitly (and other common addresses). Another one of those things where we're showcasing dev tools instead of making a product. Curious to sync on that idea if anyone thinks differently.
Resolves #122.
- …

Use AddressRegistry in inpage demo

---

account-integrations/safe/src/SafeZKPPasswordFactory.sol
account-integrations/safe/src/SafeZKPPasswordPlugin.sol
account-integrations/safe/src/SafeZkEmailRecoveryPlugin.sol
account-integrations/safe/src/interface/IDKIMRegsitry.sol
account-integrations/safe/src/interface/IGroth16Verifier.sol
account-integrations/safe/src/utils/MockDKIMRegsitry.sol
account-integrations/safe/src/utils/MockGroth16Verifier.sol
account-integrations/safe/src/utils/Safe4337Base.sol
account-integrations/safe/test/forge/SafeZkEmailRecoveryPlugin.t.sol
account-integrations/safe/test/hardhat/SafeZKPPasswordPlugin.test.ts
account-integrations/safe/test/hardhat/SafeZkEmailRecoveryPlugin.test.ts
account-integrations/safe/test/hardhat/utils/createUserOp.ts
account-integrations/safe/test/hardhat/utils/setupTests.ts

- Adds a zk email recovery plugin
- Adds forge and hardhat tests
- Mocks external components not developed yet (uses existing mock verifier)
The recovery flow is based off of the existing ecdsa recovery plugin flow. This flow will likely change in the future but serves as a goos starting point to get the zk email plugin off the ground.
Run `SafeZkEmailRecoveryPlugin.test.ts`
resolves #167 
- (But add a 'done' comment or similar)

Add zk email recovery plugin

---

account-integrations/safe/src/SafeZkEmailRecoveryPlugin.sol
account-integrations/safe/test/forge/SafeZkEmailRecoveryPlugin.t.sol
account-integrations/safe/test/hardhat/SafeCompressionPlugin.test.ts
account-integrations/safe/test/hardhat/SafeECDSAPlugin.test.ts
account-integrations/safe/test/hardhat/SafeECDSARecoveryPlugin.test.ts
account-integrations/safe/test/hardhat/SafeZKPPasswordPlugin.test.ts
account-integrations/safe/test/hardhat/SafeZkEmailRecoveryPlugin.test.ts
account-integrations/safe/test/hardhat/utils/createUserOp.ts
account-integrations/safe/test/hardhat/utils/execution.ts
account-integrations/safe/test/hardhat/utils/setupTests.ts

- Adds a default delay of 2 weeks for recovery
- Adds a configurable custom delay for recovery which overrides the default delay
- Adds a cancel recovery function. Access control for this function relies on the fact that msg.sender is the safe for which recovery should be cancelled for. We may want to add more robust access control in future work.
3 functions now need to be called in the recovery plugin to successfully rotate an owner on the ecsda plugin: `configureRecovery`, `initiateRecovery` & `recoverPlugin`. Also `setCustomDelay` if setting a custom delay.
- `configureRecovery` (previously called `addRecoveryHash`) largely does what it did before, which is storing a recovery request in the form of a `recoveryHash` and a `dkimPublicKeyHash` (other values not set on the struct until …

Add default and custom delay to zkemail recovery

---

account-integrations/safe/.vscode/settings.json
account-integrations/safe/script/deploy_all.ts
account-integrations/safe/script/patched-bundler-727838b.dockerfile
account-integrations/safe/script/start.sh
account-integrations/safe/src/SafeBlsPlugin.sol
account-integrations/safe/src/imports.sol
account-integrations/safe/test/forge/SafeBlsPlugin.t.sol
account-integrations/safe/test/forge/utils/SafeBlsPluginHarness.sol
account-integrations/safe/test/hardhat/SafeBlsPlugin.test.ts
account-integrations/safe/test/hardhat/SafeCompressionPlugin.test.ts
account-integrations/safe/test/hardhat/SafeECDSAPlugin.test.ts
account-integrations/safe/test/hardhat/SafeECDSARecoveryPlugin.test.ts
account-integrations/safe/test/hardhat/SafeWebAuthnPlugin.test.ts
account-integrations/safe/test/hardhat/SafeZKPPasswordPlugin.test.ts
account-integrations/safe/test/hardhat/SafeZkEmailRecoveryPlugin.test.ts
account-integrations/safe/test/hardhat/utils/DeterministicDeployer.ts
account-integrations/safe/test/hardhat/utils/SafeSingletonFactory.ts
account-integrations/safe/test/hardhat/utils/appendKeyToInitCode.ts
account-integrations/safe/test/hardhat/utils/getBlsUserOpHash.ts
account-integrations/safe/test/hardhat/utils/resolveUserOp.ts
account-integrations/safe/test/hardhat/utils/setupTests.ts

Updates `SafeBlsPlugin` to use aggregation via eth-infinitism's `BLSSignatureAggregator` example.
Supporting changes:
- Switch to [arachnid's deterministic deployer](https://github.com/Arachnid/deterministic-deployment-proxy) for non-safe contracts for consistency with eth-infinitism and the broader ecosystem[^1][^2]
- Add support for linked libraries to deterministic deployer
- Patch the bundler to add partial aggregation support
Run the tests per instructions ([allowing the webauthn test to fail](https://github.com/getwax/wax/issues/191)).
Contributes to #190.
- (But add a 'done' comment or similar)
[^1]: [Arachnid's deployer](https://etherscan.io/address/0x4e59b44847b379578588 …

BLS plugin: use aggregation

---

account-integrations/zkp/relayer/src/index.ts
account-integrations/zkp/relayer/src/lib/imapClient.ts
account-integrations/zkp/relayer/src/lib/smtpClient.ts
account-integrations/zkp/relayer/src/services/emailService.ts
account-integrations/zkp/relayer/src/services/ethereumService.ts
account-integrations/zkp/relayer/src/tables/emailTable.ts

Follow ups from comments on #200 & #201
- Adds `running` flag to `emailService.ts` `pollEmails()` loop instead of doing `while(true)`
- Returns more helpful information in confirmation emails
- Return some helpful info for this from ethereum service
- Adds `generateFailureEmail` and `generateSuccessEmail` in smtp client to generate emails for respective scenarios
- Adds helper functions in smtp client to format certain information in confirmation emails: `formatRevertReason` & `formatDelay`
- Other minor changes:
- typos
- use console.error
- Update `InitiateRecoveryResult` with more info and make it a union type
- better encapsulate classes
n/a
Contributes to #173 
- (But add a …

Relayer initial work follow up

---

packages/plugins/README.md
packages/plugins/package.json
packages/plugins/test/e2e/SafeZKPPasswordPlugin.test.ts
packages/plugins/test/e2e/SafeZkEmailRecoveryPlugin.test.ts

- Fix dep issues with deterministic deployer
- Skip broken tests
- Update plugins README instructions 
Setup plugin's package via README & run tests
No
- (But add a 'done' comment or similar)

Fix Plugin e2e testing issue & instructions

---

packages/plugins/src/paymaster/README.md
packages/plugins/src/paymaster/SponsorEverythingPaymaster.sol
packages/plugins/test/e2e/SafeSponsorEverythingPaymaster.test.ts
packages/plugins/test/e2e/utils/createUserOp.ts
packages/plugins/test/e2e/utils/getGasEstimates.ts

This PR adds SponsorEverythingPaymaster contract and its test, which can serve as references when developing more complex paymasters.
Its test is included in the existing plugin tests. i.e., run `yarn hardhat test` in `packages/plugins` will test the changes.
No.
- (But add a 'done' comment or similar)

Add SponsorEverythingPaymaster
